# Generated by Django 4.2.3 on 2023-07-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='defence',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='power',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speed',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
