# Generated by Django 4.2.3 on 2023-07-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_defence_userprofile_power_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='defence',
            new_name='defense',
        ),
    ]
