# Generated by Django 4.2.3 on 2023-07-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_defence_userprofile_defense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='defense',
            new_name='defence',
        ),
    ]
