# Generated by Django 4.2.3 on 2023-07-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_defense_userprofile_defence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='hp',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='mp',
            new_name='xp',
        ),
    ]
