# Generated by Django 4.2.3 on 2023-07-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('profiles', '0012_remove_userprofile_last_healed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.boots'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.shield'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.sword'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
    ]
