# Generated by Django 4.2.3 on 2023-07-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_userprofile_hourly_wage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hourly_wage',
        ),
    ]
