# Generated by Django 4.2.3 on 2023-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_userprofile_hourly_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hourly_wage',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
