# Generated by Django 4.2.3 on 2023-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_userprofile_hourly_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
