# Generated by Django 4.2.3 on 2023-07-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_userprofile_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_defence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_power',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_speed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
