# Generated by Django 4.2.3 on 2023-08-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_health_for_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_xp_for_level',
            field=models.IntegerField(default=0),
        ),
    ]
