# Generated by Django 4.2.3 on 2023-08-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_healing',
            field=models.BooleanField(default=False),
        ),
    ]
