# Generated by Django 4.2.3 on 2023-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_defencepotion_healthpotion_speedpotion'),
        ('profiles', '0022_userprofile_defence_potion_userprofile_health_potion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='defence_potion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='health_potion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='power_potion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='speed_potion',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='defence_potion',
            field=models.ManyToManyField(blank=True, null=True, to='common.defencepotion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_potion',
            field=models.ManyToManyField(blank=True, null=True, to='common.healthpotion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='power_potion',
            field=models.ManyToManyField(blank=True, null=True, to='common.powerpotion'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speed_potion',
            field=models.ManyToManyField(blank=True, null=True, to='common.speedpotion'),
        ),
    ]
