# Generated by Django 4.2.3 on 2023-08-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_defencepotion_healthpotion_speedpotion'),
        ('profiles', '0023_remove_userprofile_defence_potion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='defence_potion',
            field=models.ManyToManyField(blank=True, to='common.defencepotion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_potion',
            field=models.ManyToManyField(blank=True, to='common.healthpotion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='power_potion',
            field=models.ManyToManyField(blank=True, to='common.powerpotion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='speed_potion',
            field=models.ManyToManyField(blank=True, to='common.speedpotion'),
        ),
    ]
