# Generated by Django 4.2.3 on 2023-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_remove_userprofile_defence_potion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_health_for_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_xp_for_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
