# Generated by Django 4.2.3 on 2023-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_userprofile_max_health_for_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_xp_for_level',
            field=models.IntegerField(default=250),
        ),
    ]
