# Generated by Django 4.2.3 on 2023-08-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_alter_userprofile_max_xp_for_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='health',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_health_for_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_xp_for_level',
            field=models.IntegerField(default=0),
        ),
    ]
