# Generated by Django 4.2.3 on 2023-08-08 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_userprofile_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='health',
            field=models.FloatField(default=250, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
