# Generated by Django 4.2.3 on 2023-08-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_alter_userprofile_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_hiding',
            field=models.BooleanField(default=False),
        ),
    ]
