# Generated by Django 4.2.3 on 2023-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_userprofile_is_hiding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='defence_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='power_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speed_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
