version: '3.4'

services:
  web:
    image: dimitrovv/vampires-vs-werewolves
    command: gunicorn Vampires_vs_Werewolves.wsgi:application --bind 0.0.0.0:8000
    build: .
    volumes:
      - /tmp/Vampires_vs_Werewolves/static_root:/app/static
      - ./media:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./static_root:/app/static_root/
      - ./media:/app/media/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web

  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Celery worker service
  celery-worker:
    image: dimitrovv/vampires-vs-werewolves
    env_file:
      - .env
    command: sh -c "export DJANGO_SETTINGS_MODULE=Vampires_vs_Werewolves.settings && celery -A Vampires_vs_Werewolves worker --loglevel=info"
    depends_on:
      - web
  celery-beat:
    image: dimitrovv/vampires-vs-werewolves
    command: celery -A Vampires_vs_Werewolves beat -l info
    env_file:
      - .env
    depends_on:
      - web

volumes:
  redis-data: