# Generated by Django 4.2.3 on 2023-07-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boots',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='boots',
            name='required_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shield',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shield',
            name='required_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sword',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sword',
            name='required_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='boots',
            name='speed_bonus',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='shield',
            name='defense',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='sword',
            name='damage',
            field=models.PositiveIntegerField(default=20),
        ),
    ]