# Generated by Django 4.2.3 on 2023-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '005_work_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='boots',
            name='sell_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shield',
            name='sell_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sword',
            name='sell_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
