# Generated by Django 4.2.3 on 2023-08-03 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_customuser_options_and_more'),
        ('common', '0007_rename_defense_shield_defence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boots',
            options={'verbose_name': 'Boots', 'verbose_name_plural': 'Boots'},
        ),
        migrations.CreateModel(
            name='UserHiding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_available_hiding_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
