# Generated by Django 4.2.3 on 2023-08-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_boots_options_userhiding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHiding',
        ),
    ]
