# Generated by Django 4.2.3 on 2023-08-07 08:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0021_userprofile_is_healing'),
        ('common', '0009_delete_userhiding'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHiding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('can_stop_hiding_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Health', 'Health'), ('Power', 'Power'), ('Defence', 'Defence'), ('Speed', 'Speed')], max_length=10)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('hours_active', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('image', models.ImageField(upload_to='')),
                ('percent_bonus', models.PositiveIntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefencePotion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.potion',),
        ),
        migrations.CreateModel(
            name='PowerPotion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.potion',),
        ),
        migrations.CreateModel(
            name='SpeedPotion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.potion',),
        ),
    ]
