# Generated by Django 4.2.3 on 2023-08-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_delete_powerpotion_powerpotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerpotion',
            name='potion_ptr',
        ),
        migrations.DeleteModel(
            name='DefencePotion',
        ),
        migrations.DeleteModel(
            name='SpeedPotion',
        ),
        migrations.DeleteModel(
            name='Potion',
        ),
        migrations.DeleteModel(
            name='PowerPotion',
        ),
    ]
