# Generated by Django 4.2.3 on 2023-08-11 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0016_alter_userhiding_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacks', models.PositiveIntegerField(default=0)),
                ('attacked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks_received', to=settings.AUTH_USER_MODEL)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('attacker', 'attacked')},
            },
        ),
    ]
