# Generated by Django 4.2.3 on 2023-07-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]